name: build react app workflow
on:
  pull_request:
    types: [opened]
    branches:
    - "main"
  workflow_dispatch:
  push:
    branches:
    - "main"


jobs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm ci

    - name: lint app
      run: npm run lint

    - name: test app
      run: npm run test
