name: react workflow
on: push
jobs:
  test-react-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm i

    - name: lint app
      run: npm lint

    - name: test app
      run: npm test

  deploy_App:
    runs-on: ubuntu-latest
    needs: test-react-job
    steps:
    - name: deploying app
      run: echo "start deploying the app .........."

